/**
 * @typedef {'ADMIN' | 'CUSTOMER' | 'WORKER'} UserRole
 */

/**
 * @typedef {'DRAFT' | 'SUBMITTED' | 'UNDER_REVIEW' | 'QUOTATION_SENT' | 'AWAITING_CUSTOMER_CONFIRMATION' | 'CONFIRMED' | 'WORKERS_ASSIGNED' | 'SETUP_IN_PROGRESS' | 'EVENT_IN_PROGRESS' | 'EVENT_COMPLETED' | 'FINAL_PAYMENT_PENDING' | 'COMPLETED' | 'CLOSED' | 'CANCELLED' | 'REJECTED' | 'REFUND_PENDING' | 'REFUNDED'} OrderStatus
 */

/**
 * @typedef {'LED_TECHNICIAN' | 'CAMERA_OPERATOR' | 'SOUND_ENGINEER' | 'STREAMING_OPERATOR' | 'LIGHTING_TECHNICIAN' | 'GENERAL_TECHNICIAN'} WorkerSkill
 */

/**
 * @typedef {'AVAILABLE' | 'UNAVAILABLE' | 'ON_LEAVE' | 'BUSY'} WorkerAvailabilityStatus
 */

export const ORDER_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  QUOTATION_SENT: 'QUOTATION_SENT',
  AWAITING_CUSTOMER_CONFIRMATION: 'AWAITING_CUSTOMER_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  WORKERS_ASSIGNED: 'WORKERS_ASSIGNED',
  SETUP_IN_PROGRESS: 'SETUP_IN_PROGRESS',
  EVENT_IN_PROGRESS: 'EVENT_IN_PROGRESS',
  EVENT_COMPLETED: 'EVENT_COMPLETED',
  FINAL_PAYMENT_PENDING: 'FINAL_PAYMENT_PENDING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
};

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  WORKER: 'WORKER',
};

export const WORKER_SKILLS = {
  LED_TECHNICIAN: 'LED Technician',
  CAMERA_OPERATOR: 'Camera Operator',
  SOUND_ENGINEER: 'Sound Engineer',
  STREAMING_OPERATOR: 'Live Streaming Operator',
  LIGHTING_TECHNICIAN: 'Lighting Technician',
  GENERAL_TECHNICIAN: 'General Technician',
};
