export const POPULAR_BANKS = [
  {
    id: 'HDFC',
    name: 'HDFC Bank',
    code: 'HDFC',
    url: 'https://netbanking.hdfcbank.com/netbanking/',
    razorpayCode: 'HDFC',
    icon: '🏦',
    color: '#004B8D',
  },
  {
    id: 'SBI',
    name: 'State Bank of India',
    code: 'SBIN',
    url: 'https://merchant.onlinesbi.sbi/merchant/login.htm',
    razorpayCode: 'SBIN',
    icon: '🏛️',
    color: '#280071',
  },
  {
    id: 'ICICI',
    name: 'ICICI Bank',
    code: 'ICIC',
    url: 'https://infinity.icicibank.com/corporate/LoginToInbox.jsp',
    razorpayCode: 'ICIC',
    icon: '💼',
    color: '#F37023',
  },
  {
    id: 'AXIS',
    name: 'Axis Bank',
    code: 'UTIB',
    url: 'https://m.axisbank.com/Retail/Login',
    razorpayCode: 'UTIB',
    icon: '🏢',
    color: '#97144D',
  },
  {
    id: 'KOTAK',
    name: 'Kotak Mahindra Bank',
    code: 'KKBK',
    url: 'https://netbanking.kotak.com/knb2/',
    razorpayCode: 'KKBK',
    icon: '🔴',
    color: '#ED1C24',
  },
];
