export const ROLES = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  WORKER: 'WORKER',
};

export const ORDER_STATES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  QUOTATION_SENT: 'QUOTATION_SENT',
  AWAITING_CUSTOMER_CONFIRMATION: 'AWAITING_CUSTOMER_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  WORKERS_ASSIGNED: 'WORKERS_ASSIGNED',
  SETUP_IN_PROGRESS: 'SETUP_IN_PROGRESS',
  EVENT_IN_PROGRESS: 'EVENT_IN_PROGRESS',
  EVENT_COMPLETED: 'EVENT_COMPLETED',
  FINAL_PAYMENT_PENDING: 'FINAL_PAYMENT_PENDING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
};

export const VALID_ORDER_TRANSITIONS = {
  DRAFT: ['SUBMITTED', 'CANCELLED'],
  SUBMITTED: ['UNDER_REVIEW', 'CANCELLED', 'REJECTED'],
  UNDER_REVIEW: ['QUOTATION_SENT', 'REJECTED', 'CANCELLED'],
  QUOTATION_SENT: ['AWAITING_CUSTOMER_CONFIRMATION'],
  AWAITING_CUSTOMER_CONFIRMATION: ['CONFIRMED', 'REJECTED', 'CANCELLED'],
  CONFIRMED: ['WORKERS_ASSIGNED', 'CANCELLED'],
  WORKERS_ASSIGNED: ['SETUP_IN_PROGRESS', 'CANCELLED'],
  SETUP_IN_PROGRESS: ['EVENT_IN_PROGRESS', 'CANCELLED'],
  EVENT_IN_PROGRESS: ['EVENT_COMPLETED'],
  EVENT_COMPLETED: ['FINAL_PAYMENT_PENDING'],
  FINAL_PAYMENT_PENDING: ['COMPLETED'],
  COMPLETED: ['CLOSED'],
  CANCELLED: ['REFUND_PENDING', 'CLOSED'],
  REFUND_PENDING: ['REFUNDED'],
  REFUNDED: ['CLOSED'],
  REJECTED: ['CLOSED'],
};

export const WORKER_SKILLS = [
  'LED_TECHNICIAN',
  'CAMERA_OPERATOR',
  'SOUND_ENGINEER',
  'STREAMING_OPERATOR',
  'LIGHTING_TECHNICIAN',
  'GENERAL_TECHNICIAN'
];
